### ISSUE TITLE
error appear when execute "sh compile_python3.5_unix.sh" in mac os

### ISSUE THREAD

**Issue by chengcx1019** [jonathantompson/matlabnoise#4]

**Comment by jonathantompson** [comment]
What is the error?

**Comment by chengcx1019** [comment]
error messages:
Undefined symbols for architecture x86_64:
"_PyArg_UnpackTuple", referenced from:
      _wrap_Perlin2D(_object*, _object*) in matlabnoise_wrap.o
      _wrap_Perlin3D(_object*, _object*) in matlabnoise_wrap.o
      _wrap_Perlin4D(_object*, _object*) in matlabnoise_wrap.o
      _wrap_Perlin2DDeriv(_object*, _object*) in matlabnoise_wrap.o
      _wrap_Perlin3DDeriv(_object*, _object*) in matlabnoise_wrap.o
      _wrap_Hermite2D(_object*, _object*) in matlabnoise_wrap.o
      _wrap_Hermite3D(_object*, _object*) in matlabnoise_wrap.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by chengcx1019** [comment]
Actually,the error occurs when execute" g++ -shared  matlabnoise_wrap.o -o _matlabnoise.so ".

**Comment by jonathantompson** [comment]
Firstly, the name of the file is compile_python3.5_**unix**.sh, I've never compiled this on mac os x.

Secondly, it looks like you're missing the python lib wrappers. You might want to look up where they are on Mac OS X and add them to the g++ call.
